language: python
os: linux
dist: focal
services:
  - docker
addons:
  apt:
    packages:
      - python3.8-dev
      - libpq-dev

python:
  - "3.7"
  - "3.8"
  - "nightly"

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - docker-compose run djangoblog python manage.py test
  - python manage.py test
