language: python
os: linux
dist: focal
services:
  - docker
python:
  - "3.7"
  - "3.8"
  - "nightly"

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - docker-compose run web python manage.py test
