version: "3.4"

services:
  web:
    image: fantastic-django-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - /app
    environment:
      DJANGO_SUPERUSER_USERNAME: appuser
      DJANGO_SUPERUSER_PASSWORD: test
      DJANGO_SUPERUSER_EMAIL: test@test.com

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
  redis:
    image: redis:latest
    restart: always

  celery:
    build: .
    command: celery -A djangoblog worker  -l info
    restart: always
    depends_on:
      - redis
      - web
    volumes:
      - /app
  celery-beat:
    build: .
    command: celery -A djangoblog beat -l info
    restart: always
    depends_on:
      - redis
      - web
    volumes:
      - /app

volumes:
  db-data:
